### PR TITLE
Feature/backend finalize

### PR DESCRIPTION
**Pull request by TorinAsakura**
blocked by #151

### CODE REVIEW

**Comment by TFK70** [comment]
@TorinAsakura 

```javascript
Warning: componentWillMount has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: WithEmotion
    at WithEmotion (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-app-with-emotion-npm-0.2.62-b65e17211c-223d00639a.zip/node_modules/@atlantis-lab/next-app-with-emotion/dist/with-emotion.provider.js:35:104)
    at IntlProvider (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-intl-virtual-599f39d59c/0/cache/react-intl-npm-5.3.2-c3f135f3e5-2419e3634c.zip/node_modules/react-intl/src/components/provider.js:91:47)
    at WithIntl (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-app-with-intl-npm-0.2.67-64a43a6081-c364d8cfa7.zip/node_modules/@atlantis-lab/next-app-with-intl/dist/with-intl.provider.js:42:9)
    at WithUser (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-app-with-user-npm-0.2.63-8d5ebf7052-b9899df11b.zip/node_modules/@atlantis-lab/next-app-with-user/dist/with-user.provider.js:34:44)
    at WithAuth (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-app-with-auth-npm-0.2.63-1c6dc455a7-96603a0468.zip/node_modules/@atlantis-lab/next-app-with-auth/dist/with-auth.provider.js:34:44)
Error while running `getDataFromTree` Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
    at Object.invariant (webpack-internal:///../../../../.yarn/cache/@formatjs-intl-utils-npm-3.8.4-10ce4ec535-00d9d14667.zip/node_modules/@formatjs/intl-utils/src/invariant.js:7:15)
    at Object.invariantIntlContext (webpack-internal:///../../../../.yarn/$$virtual/react-intl-virtual-9e8ba99a56/0/cache/react-intl-npm-5.3.2-c3f135f3e5-2419e3634c.zip/node_modules/react-intl/src/utils.js:32:18)
    at useIntl (webpack-internal:///../../../../.yarn/$$virtual/react-intl-virtual-9e8ba99a56/0/cache/react-intl-npm-5.3.2-c3f135f3e5-2419e3634c.zip/node_modules/react-intl/src/components/useIntl.js:8:13)
    at Seo (webpack-internal:///../../index-page/src/Seo.tsx:19:74)
    at processChild (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToStaticMarkup (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at /Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/@apollo-client-virtual-96e41d0132/0/cache/@apollo-client-npm-3.3.19-39baf9f99e-a7266cfdff.zip/node_modules/@apollo/client/react/ssr/getDataFromTree.js:20:21
    at new Promise (<anonymous>)
    at process (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/@apollo-client-virtual-96e41d0132/0/cache/@apollo-client-npm-3.3.19-39baf9f99e-a7266cfdff.zip/node_modules/@apollo/client/react/ssr/getDataFromTree.js:18:16)
Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
    at Object.invariant (webpack-internal:///../../../../.yarn/cache/@formatjs-intl-utils-npm-3.8.4-10ce4ec535-00d9d14667.zip/node_modules/@formatjs/intl-utils/src/invariant.js:7:15)
    at Object.invariantIntlContext (webpack-internal:///../../../../.yarn/$$virtual/react-intl-virtual-9e8ba99a56/0/cache/react-intl-npm-5.3.2-c3f135f3e5-2419e3634c.zip/node_modules/react-intl/src/utils.js:32:18)
    at useIntl (webpack-internal:///../../../../.yarn/$$virtual/react-intl-virtual-9e8ba99a56/0/cache/react-intl-npm-5.3.2-c3f135f3e5-2419e3634c.zip/node_modules/react-intl/src/components/useIntl.js:8:13)
    at Seo (webpack-internal:///../../index-page/src/Seo.tsx:19:74)
    at processChild (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-99c3960f41/0/cache/next-npm-10.0.5-716eec629b-fa8a4c872b.zip/node_modules/next/next-server/server/render.tsx:963:18)
    at Function.getInitialProps (webpack-internal:///../../../../.yarn/$$virtual/next-virtual-99c3960f41/0/cache/next-npm-10.0.5-716eec629b-fa8a4c872b.zip/node_modules/next/dist/pages/_document.js:135:19)
    at Function.<anonymous> (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-document-with-helmet-npm-0.2.8-bbab988cc4-b7d331d13b.zip/node_modules/@atlantis-lab/next-document-with-helmet/dist/with-helmet.provider.js:23:49)
    at Generator.next (<anonymous>)
    at /Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-document-with-helmet-npm-0.2.8-bbab988cc4-b7d331d13b.zip/node_modules/@atlantis-lab/next-document-with-helmet/dist/with-helmet.provider.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-document-with-helmet-npm-0.2.8-bbab988cc4-b7d331d13b.zip/node_modules/@atlantis-lab/next-document-with-helmet/dist/with-helmet.provider.js:4:12)
```

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> 
> ```js
> Warning: componentWillMount has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.
> 
> * Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.
> 
> Please update the following components: WithEmotion
>     at WithEmotion (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-app-with-emotion-npm-0.2.62-b65e17211c-223d00639a.zip/node_modules/@atlantis-lab/next-app-with-emotion/dist/with-emotion.provider.js:35:104)
>     at IntlProvider (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-intl-virtual-599f39d59c/0/cache/react-intl-npm-5.3.2-c3f135f3e5-2419e3634c.zip/node_modules/react-intl/src/components/provider.js:91:47)
>     at WithIntl (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-app-with-intl-npm-0.2.67-64a43a6081-c364d8cfa7.zip/node_modules/@atlantis-lab/next-app-with-intl/dist/with-intl.provider.js:42:9)
>     at WithUser (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-app-with-user-npm-0.2.63-8d5ebf7052-b9899df11b.zip/node_modules/@atlantis-lab/next-app-with-user/dist/with-user.provider.js:34:44)
>     at WithAuth (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-app-with-auth-npm-0.2.63-1c6dc455a7-96603a0468.zip/node_modules/@atlantis-lab/next-app-with-auth/dist/with-auth.provider.js:34:44)
> Error while running `getDataFromTree` Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
>     at Object.invariant (webpack-internal:///../../../../.yarn/cache/@formatjs-intl-utils-npm-3.8.4-10ce4ec535-00d9d14667.zip/node_modules/@formatjs/intl-utils/src/invariant.js:7:15)
>     at Object.invariantIntlContext (webpack-internal:///../../../../.yarn/$$virtual/react-intl-virtual-9e8ba99a56/0/cache/react-intl-npm-5.3.2-c3f135f3e5-2419e3634c.zip/node_modules/react-intl/src/utils.js:32:18)
>     at useIntl (webpack-internal:///../../../../.yarn/$$virtual/react-intl-virtual-9e8ba99a56/0/cache/react-intl-npm-5.3.2-c3f135f3e5-2419e3634c.zip/node_modules/react-intl/src/components/useIntl.js:8:13)
>     at Seo (webpack-internal:///../../index-page/src/Seo.tsx:19:74)
>     at processChild (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
>     at resolve (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
>     at ReactDOMServerRenderer.render (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
>     at ReactDOMServerRenderer.read (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
>     at renderToStaticMarkup (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
>     at /Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/@apollo-client-virtual-96e41d0132/0/cache/@apollo-client-npm-3.3.19-39baf9f99e-a7266cfdff.zip/node_modules/@apollo/client/react/ssr/getDataFromTree.js:20:21
>     at new Promise (<anonymous>)
>     at process (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/@apollo-client-virtual-96e41d0132/0/cache/@apollo-client-npm-3.3.19-39baf9f99e-a7266cfdff.zip/node_modules/@apollo/client/react/ssr/getDataFromTree.js:18:16)
> Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
>     at Object.invariant (webpack-internal:///../../../../.yarn/cache/@formatjs-intl-utils-npm-3.8.4-10ce4ec535-00d9d14667.zip/node_modules/@formatjs/intl-utils/src/invariant.js:7:15)
>     at Object.invariantIntlContext (webpack-internal:///../../../../.yarn/$$virtual/react-intl-virtual-9e8ba99a56/0/cache/react-intl-npm-5.3.2-c3f135f3e5-2419e3634c.zip/node_modules/react-intl/src/utils.js:32:18)
>     at useIntl (webpack-internal:///../../../../.yarn/$$virtual/react-intl-virtual-9e8ba99a56/0/cache/react-intl-npm-5.3.2-c3f135f3e5-2419e3634c.zip/node_modules/react-intl/src/components/useIntl.js:8:13)
>     at Seo (webpack-internal:///../../index-page/src/Seo.tsx:19:74)
>     at processChild (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
>     at resolve (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
>     at ReactDOMServerRenderer.render (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
>     at ReactDOMServerRenderer.read (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
>     at renderToString (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-59f6eb3c79/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
>     at Object.renderPage (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-99c3960f41/0/cache/next-npm-10.0.5-716eec629b-fa8a4c872b.zip/node_modules/next/next-server/server/render.tsx:963:18)
>     at Function.getInitialProps (webpack-internal:///../../../../.yarn/$$virtual/next-virtual-99c3960f41/0/cache/next-npm-10.0.5-716eec629b-fa8a4c872b.zip/node_modules/next/dist/pages/_document.js:135:19)
>     at Function.<anonymous> (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-document-with-helmet-npm-0.2.8-bbab988cc4-b7d331d13b.zip/node_modules/@atlantis-lab/next-document-with-helmet/dist/with-helmet.provider.js:23:49)
>     at Generator.next (<anonymous>)
>     at /Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-document-with-helmet-npm-0.2.8-bbab988cc4-b7d331d13b.zip/node_modules/@atlantis-lab/next-document-with-helmet/dist/with-helmet.provider.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atlantis-lab-next-document-with-helmet-npm-0.2.8-bbab988cc4-b7d331d13b.zip/node_modules/@atlantis-lab/next-document-with-helmet/dist/with-helmet.provider.js:4:12)
> ```

fixed on https://github.com/atls/nextjs/pull/199

**Comment by TFK70** [comment]
@TorinAsakura сейчас застрял на этом:

<details>
```javascript
info  - Generating static pages (1/1)

> Build error occurred
Error: Export encountered errors on following paths:
        /500
    at /Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-cb62d76250/0/cache/next-npm-10.2.3-e1de0387ed-e32ff7cc79.zip/node_modules/next/dist/export/index.js:31:1106
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Span.traceAsyncFn (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-cb62d76250/0/cache/next-npm-10.2.3-e1de0387ed-e32ff7cc79.zip/node_modules/next/dist/telemetry/trace/trace.js:6:584)
    at async /Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-cb62d76250/0/cache/next-npm-10.2.3-e1de0387ed-e32ff7cc79.zip/node_modules/next/dist/build/index.js:45:49
    at async Span.traceAsyncFn (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-cb62d76250/0/cache/next-npm-10.2.3-e1de0387ed-e32ff7cc79.zip/node_modules/next/dist/telemetry/trace/trace.js:6:584)
    at async /Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-cb62d76250/0/cache/next-npm-10.2.3-e1de0387ed-e32ff7cc79.zip/node_modules/next/dist/build/index.js:27:1475
    at async Span.traceAsyncFn (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-cb62d76250/0/cache/next-npm-10.2.3-e1de0387ed-e32ff7cc79.zip/node_modules/next/dist/telemetry/trace/trace.js:6:584)
Internal Error: Command failed with exit code 1: yarn next build src
    at makeError (/Users/darius/workspace/atlantis/serenity/.yarn/cache/execa-npm-5.0.0-4ee568fb49-bf9664702c.zip/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/darius/workspace/atlantis/serenity/.yarn/cache/execa-npm-5.0.0-4ee568fb49-bf9664702c.zip/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RendererBuildCommand.execute (/Users/darius/workspace/atlantis/serenity/.yarn/cache/@atls-actl-renderer-npm-0.0.1-22ba705ee2-59dfeecf8f.zip/node_modules/@atls/actl-renderer/dist/renderer-build.command.js:27:9)
    at async RendererBuildCommand.validateAndExecute (/Users/darius/workspace/atlantis/serenity/.yarn/cache/clipanion-npm-2.6.2-65049fe240-d162deedd0.zip/node_modules/clipanion/lib/index.js:1118:26)
    at async Cli.run (/Users/darius/workspace/atlantis/serenity/.yarn/cache/clipanion-npm-2.6.2-65049fe240-d162deedd0.zip/node_modules/clipanion/lib/index.js:1371:24)
    at async Cli.runExit (/Users/darius/workspace/atlantis/serenity/.yarn/cache/clipanion-npm-2.6.2-65049fe240-d162deedd0.zip/node_modules/clipanion/lib/index.js:1388:28)
```
</details>


Если честно это не выглядит как проблема с зависимостями/срцами, скорее что-то с вебпаком

**Comment by TFK70** [comment]
### Состояние

Некорректно маунтятся компоненты из воркспейсов, вследствие чего useIntl не получает объект intl из провайдера

`yarn workspace @site/app build` - для воспроизведения

<details>

```javascript
Exporting (1/7)Error while running `getDataFromTree` Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
    at Object.invariant (/Users/darius/workspace/atlantis/serenity/frontend/site/app/src/.next/server/pages/_app.js:12027:15)
    at Object.invariantIntlContext (/Users/darius/workspace/atlantis/serenity/frontend/site/app/src/.next/server/pages/_app.js:1101:18)
    at useIntl (/Users/darius/workspace/atlantis/serenity/frontend/site/app/src/.next/server/pages/_app.js:12106:13)
    at Seo (/Users/darius/workspace/atlantis/serenity/frontend/site/app/src/.next/server/pages/index.js:51586:45)
    at d (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-5595ada018/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-5595ada018/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-5595ada018/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-5595ada018/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToStaticMarkup (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/react-dom-virtual-5595ada018/0/cache/react-dom-npm-17.0.2-f551215af1-960a74ff66.zip/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:51:446)
    at /Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/@apollo-client-virtual-120be58cda/0/cache/@apollo-client-npm-3.3.19-39baf9f99e-a7266cfdff.zip/node_modules/@apollo/client/react/ssr/ssr.cjs.js:85:21
```

</details>

Если захардкодить в pages страницы подобной структуры:

```javascript
import { createElement } from 'react'
import { useIntl } from 'react-intl'

const Component = () => {
   console.log(useIntl())
   return createElement('p',{},'test')
}

export default Component
```

Проект сбилдится и в логах будет валидный объект intl (из этого следует что как минимум провайдер не битый)

Воспроизводится в изолированной среде

**Comment by TorinAsakura** [comment]
> ### Состояние
> Некорректно маунтятся компоненты из воркспейсов, вследствие чего useIntl не получает объект intl из провайдера
> 
> `yarn workspace @site/app build` - для воспроизведения
> 
> Если захардкодить в pages страницы подобной структуры:
> 
> ```js
> import { createElement } from 'react'
> import { useIntl } from 'react-intl'
> 
> const Component = () => {
>    console.log(useIntl())
>    return createElement('p',{},'test')
> }
> 
> export default Component
> ```
> 
> Проект сбилдится и в логах будет валидный объект intl (из этого следует что как минимум провайдер не битый)
> 
> Воспроизводится в изолированной среде

выглядит так, будто тут несколько инстансов (предположительно), можно посмотреть через yarn why react-intl, зафиксить можно попробовать таким образом https://github.com/atls/examples/blob/master/grpc-playground/applications/renderer/next.config.js#L12

**Comment by TFK70** [comment]
### Состояние

<details>

```javascript
ModuleNotFoundError: Module not found: Error: Can't resolve '@apollo/client/core' in '/Users/darius/workspace/atlantis/serenity/.yarn/cache/@apollo-link-error-npm-2.0.0-beta.3-4aea365499-76cb027479.zip/node_modules/@apollo/link-error/lib'
```

</details>

Очень странная ошибка которая не резолвится алиасами, packageExtension'ами и резолюшнами
В самом тексте ошибки все сказано, он просто не может добраться до модуля несмотря на его присутствие в dependencies у пакета

Реальную природу ошибки на данный момент мне даже предположить трудно, скорее всего ноги растут от того что "физически" зависимость не присутствует, вместо этого только мапа на нее, из-за чего обращения по типу `@apollo/client/react/ssr` (когда основная зависимость - `@apollo/client`) тупо ломаются выдавая как результат такую ошибку

Пока думаю что это можно решить средствами вебпака, похожим с алиасами способом, он все-таки на этапе сборки не может до пакета достучаться

## Причина

Алиасы по какой-то причине ломали импорт
По идее алиас `@apollo/client` должен перенаправлять `@apollo/client/react/ssr` в нужный инстанс, в целом это он сделать и пытался, но что-то там шло не так

Решилось добавив строгие алиасы с помощью `$`(`@apollo/client$`), чтобы перенаправлялся только импорт`@apollo/client`, позже добавив то же самое для @apollo/client/react/ssr (тоже с `$`) - сайт сбилдился

**Comment by TFK70** [comment]
### Состояние

`yarn workspace @site/app build` - успех

<details>

```javascript
Page                             Size     First Load JS
┌ λ /                            3.39 kB         375 kB
├   /_app                        0 B             234 kB
├ λ /404                         1.25 kB         235 kB
├ λ /projects                    3.45 kB         383 kB
├ λ /projects/[id]               17.4 kB         413 kB
├ λ /specialists                 5.52 kB         385 kB
└ λ /specialists/[id]            8.54 kB         358 kB
+ First Load JS shared by all    234 kB
  ├ chunks/framework.97141d.js   84.6 kB
  ├ chunks/main.dcc7e6.js        19.6 kB
  ├ chunks/pages/_app.33ed5d.js  128 kB
  └ chunks/webpack.277c75.js     1.04 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
info  - using build directory: /Users/darius/workspace/atlantis/serenity/frontend/site/app/src/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
info  - Launching 11 workers
info  - Exporting (7/7)
Export successful. Files written to /Users/darius/workspace/atlantis/serenity/frontend/site/app/dist
```

</details>

С одинаковой ошибкой падают dev и start скрипты, но тут все вроде как понятно, нужно с вебпак конфигом немного поиграть

<details>

```javascript
● [start-server] running `node /Users/darius/workspace/atlantis/serenity/frontend/site/app/dist/index.js`
● [start-server:monitor] Handling Hot Module Reloading
● [start-server] Script loaded
● [start-server:monitor] Cannot find update.
●  info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
●  (node:87149) UnhandledPromiseRejectionWarning: Error: > Couldn't find a `pages` directory. Please create one under the project root
●      at findPagesDir (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-cb62d76250/0/cache/next-npm-10.2.3-e1de0387ed-e32ff7cc79.zip/node_modules/next/dist/lib/fin
   d-pages-dir.js:3:170)

●      at new DevServer (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-cb62d76250/0/cache/next-npm-10.2.3-e1de0387ed-e32ff7cc79.zip/node_modules/next/dist/server
   /next-dev-server.js:2:1761)
●      at NextServer.createServer
   (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-cb62d76250/0/cache/next-npm-10.2.3-e1de0387ed-e32ff7cc79.zip/node_modules/next/dist/server/next.js:1:2904)
●      at /Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-cb62d76250/0/cache/next-npm-10.2.3-e1de0387ed-e32ff7cc79.zip/node_modules/next/dist/server/next.js:1:3371
●      at async NextServer.prepare
   (/Users/darius/workspace/atlantis/serenity/.yarn/$$virtual/next-virtual-cb62d76250/0/cache/next-npm-10.2.3-e1de0387ed-e32ff7cc79.zip/node_modules/next/dist/server/next.js:1:2679)
●      at async bootstrap (webpack-internal:///./frontend/site/app/src/index.ts:17:5)
●  (Use `node --trace-warnings ...` to show where the warning was created)
●  (node:87149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting
   a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see
   https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
●  (node:87149) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with
   a non-zero exit code.
```

</details>

upd: скрипты завелись

**Review by TFK70 — APPROVED** [review]

**Pull request merged**
